//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasseAcessaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoas
    {
        public int Id_pessoa { get; set; }
        public string Nome_pessoa { get; set; }
        public string Sobrenome_pessoa { get; set; }
        public string Endereco_pessoa { get; set; }
        public string Telefone_pessoa { get; set; }
        public string Email_pessoa { get; set; }
        public System.DateTime DataCadastro_pessoa { get; set; }
        public Nullable<System.DateTime> DataAltCadastro_pessoa { get; set; }
    }
}
